{% set name = "fps-nbconvert" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_nbconvert-{{ version }}.tar.gz
  sha256: 1face875c37cbdd171de7ca6b9b2018e16c9ebc394f22d3cc0d52cebb0da1b66

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.9.0,<0.10.0
    - nbconvert

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_nbconvert

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/nbconvert
  summary: An FPS plugin for the nbconvert API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/nbconvert
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
