{% set name = "fps-nbconvert" %}
{% set version = "0.0.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_nbconvert-{{ version }}.tar.gz
  sha256: 84ae6058f09d9036a7cfd40fe54b2eed5cd9968d99a52af8d14b37544af76ac2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fps <1
    - fps-auth <1
    - nbconvert >=6,<7

test:
  imports:
    - fps_nbconvert

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/nbconvert
  summary: An FPS plugin for the nbconvert API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/nbconvert
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
