{% set name = "fps-nbconvert" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_nbconvert-{{ version }}.tar.gz
  sha256: bcf6590013601be8d36bf07886e6880fcddeb12e68fb9bb7a1a7284f027b2198

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.7.0,<1
    - nbconvert

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_nbconvert

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/nbconvert
  summary: An FPS plugin for the nbconvert API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/nbconvert
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
