schema_version: 1

context:
  version: "0.10.1"

package:
  name: fps-nbconvert
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fps-nbconvert/fps_nbconvert-${{ version }}.tar.gz
    sha256: 32bf96974eba41da61c7a4608fc3f5fb467e456f23621f09d36570d7ee0485b3

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - fastapi-core
    - fps
    - jupyverse-api >=0.15.0,<0.16.0
    - jupyverse-auth >=0.2.0,<0.3.0
    - jupyverse-nbconvert >=0.1.0,<0.2.0
    - nbconvert

tests:
  - python:
      imports: fps_nbconvert
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/nbconvert
  summary: An FPS plugin for the nbconvert API

extra:
  recipe-maintainers:
    - davidbrochart
